#!/bin/bash

# Colors for text
RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
RESET='\033[0m'

title() {
	local text="$1"
	echo -e "${CYAN}${text}${RESET}:"
}

# Gets Hostname of machine
hostname=$(hostname)

# Below assigns variables for RAM usage
total=$(free -h | awk 'FNR == 2 {print $2}')
used=$(free -h | awk 'FNR == 2 {print $3}')

os=$(lsb_release -a | awk 'FNR == 2 {print $2 " " $3 " " $4}')
uptime=$(uptime -p | awk '{for (i=2; i<=NF; i++) printf "%s%s", $i, (i==NF ? "\n" : " ")}')
stg_free=$(df -h | awk 'FNR == 3 {print $3}')
stg_total=$(df -h | awk 'FNR ==3 {print $2}')

printf "$(title "Hostname") $hostname\n"
printf "$(title "Memory") ${RED}%s${RESET} / %s\n" "$used" "$total" 
printf "$(title "OS") %s\n" "$os"
printf "$(title "Uptime") %s\n" "$uptime"
printf "$(title "Storage") ${GREEN}%s${RESET} / %s\n" "$stg_free" "$stg_total"



# +--------------------------------------------------+
# |  !!! USE FOR FUTURE REFERENCE FOR FORMATTING !!! | 
# +--------------------------------------------------+
#label="$(title "Storage")"
#upLabel="$(title "Uptime")"
#printf "%-25s %s\n" "$upLabel" "$uptime"
#printf "%-25s %b / %s\n" "$label" "${GREEN}${stg_free}${RESET}" "$stg_total"

